/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Irwan080525;

/**
 *
 * @author Pongo
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    public FormStudent() {
        initComponents();
        this.clearForm();
    }
    
    // Fungsi membersihkan layar
    
    public void clearForm(){
        txtNama.setText("");
        txtAlamat.setText("");
        txtUmur.setText("");
        txtMatematika.setText("");
        txtBhsInggris.setText("");
        txtIlmuPengetahuan.setText("");
        txtRataRata.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRataRata = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtUmur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        txtBhsInggris = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIlmuPengetahuan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtRataRata.setText("jTextField7");
        txtRataRata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRataRataActionPerformed(evt);
            }
        });
        getContentPane().add(txtRataRata);
        txtRataRata.setBounds(210, 330, 380, 22);

        txtNama.setText("jTextField1");
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(210, 30, 380, 22);

        txtAlamat.setText("jTextField2");
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(210, 70, 380, 22);

        txtUmur.setText("jTextField3");
        txtUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmurActionPerformed(evt);
            }
        });
        getContentPane().add(txtUmur);
        txtUmur.setBounds(210, 110, 380, 22);

        jLabel1.setText("Rata-rata");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 330, 80, 16);

        jLabel2.setText("Nama ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 80, 16);

        jLabel3.setText("Alamat ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 16);

        jLabel4.setText("Umur ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 80, 16);

        jLabel5.setText("Matematika ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 80, 16);

        jLabel6.setText("Bhs. Inggris");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 190, 80, 16);

        txtMatematika.setText("jTextField4");
        txtMatematika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatematikaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatematika);
        txtMatematika.setBounds(210, 150, 380, 22);

        txtBhsInggris.setText("jTextField5");
        txtBhsInggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBhsInggrisActionPerformed(evt);
            }
        });
        getContentPane().add(txtBhsInggris);
        txtBhsInggris.setBounds(210, 190, 380, 22);

        btnProses.setBackground(new java.awt.Color(153, 153, 153));
        btnProses.setForeground(new java.awt.Color(51, 51, 51));
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(25, 280, 570, 23);

        jLabel7.setText("Ilmu Pengetahuan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 230, 80, 16);

        txtIlmuPengetahuan.setText("jTextField6");
        txtIlmuPengetahuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIlmuPengetahuanActionPerformed(evt);
            }
        });
        getContentPane().add(txtIlmuPengetahuan);
        txtIlmuPengetahuan.setBounds(210, 230, 380, 22);

        setSize(new java.awt.Dimension(651, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRataRataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRataRataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRataRataActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmurActionPerformed

    private void txtMatematikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatematikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatematikaActionPerformed

    private void txtBhsInggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBhsInggrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBhsInggrisActionPerformed

    private void txtIlmuPengetahuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIlmuPengetahuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIlmuPengetahuanActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        StudentRecord student = new StudentRecord();
        student.setName(txtNama.getText());
        student.setAddress(txtAlamat.getText());
        student.setAge( Integer.parseInt(txtUmur.getText()));
        student.setMathGrade( Double.parseDouble(txtMatematika.getText()));
        student.setEnglishGrade( Double.parseDouble(txtBhsInggris.getText()));
        student.setScienceGrade( Double.parseDouble(txtIlmuPengetahuan.getText()));
        txtRataRata.setText( String.valueOf(student.getAverage()));
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBhsInggris;
    private javax.swing.JTextField txtIlmuPengetahuan;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtRataRata;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
